export const CategoryTypes = {
  GET_CATEGORY: "GET_CATEGORY",
  GET_CATEGORY_PENDING: "GET_CATEGORY_PENDING",
  GET_CATEGORY_FULFILLED: "GET_CATEGORY_FULFILLED",
  GET_CATEGORY_REJECTED: "GET_CATEGORY_REJECTED",

  GET_CATEGORY_EVENT: "GET_CATEGORY_EVENT",
  GET_CATEGORY_EVENT_PENDING: "GET_CATEGORY_EVENT_PENDING",
  GET_CATEGORY_EVENT_FULFILLED: "GET_CATEGORY_EVENT_FULFILLED",
  GET_CATEGORY_EVENT_REJECTED: "GET_CATEGORY_EVENT_REJECTED",

  GET_CATEGORY_ID: "GET_CATEGORY_ID",
  GET_CATEGORY_ID_PENDING: "GET_CATEGORY_ID_PENDING",
  GET_CATEGORY_ID_FULFILLED: "GET_CATEGORY_ID_FULFILLED",
  GET_CATEGORY_ID_REJECTED: "GET_CATEGORY_ID_REJECTED"
};

export const OrderTypes = {
  GET_PAYMENT: "GET_PAYMENT",
  GET_PAYMENT_PENDING: "GET_PAYMENT_PENDING",
  GET_PAYMENT_FULFILLED: "GET_PAYMENT_FULFILLED",
  GET_PAYMENT_REJECTED: "GET_PAYMENT_REJECTED",

  GET_MYTICKET: "GET_MYTICKET",
  GET_MYTICKET_PENDING: "GET_MYTICKET_PENDING",
  GET_MYTICKET_FULFILLED: "GET_MYTICKET_FULFILLED",
  GET_MYTICKET_REJECTED: "GET_MYTICKET_REJECTED",

  EDIT_TO_CONFIRMED: "EDIT_TO_CONFIRMED",

  ADD_TICKET: "ADD_TICKET"
};

export const EventTypes = {
  GET_EVENT: "GET_EVENT",
  GET_EVENT_PENDING: "GET_EVENT_PENDING",
  GET_EVENT_FULFILLED: "GET_EVENT_FULFILLED",
  GET_EVENT_REJECTED: "GET_EVENT_REJECTED",

  GET_DETAILE_EVENT: "GET_DETAILE_EVENT",
  GET_DETAILE_EVENT_PENDING: "GET_DETAILE_EVENT_PENDING",
  GET_DETAILE_EVENT_FULFILLED: "GET_DETAILE_EVENT_FULFILLED",
  GET_DETAILE_EVENT_REJECTED: "GET_DETAILE_EVENT_REJECTED",

  ADD_EVENT: "ADD_EVENT"
};

export const userTypes = {
  GET_USER: "GET_USER",
  GET_USER_FULFILLED: "GET_USER_FULFILLED",
  GET_USER_REJECTED: "GET_USER_REJECTED",
  GET_USER_PENDING: "GET_USER_PENDING",
  CHANGE_USER: "CHANGE_USER"
};
