export const CategoryTypes = {
  GET_CATEGORY: "GET_CATEGORY",
  GET_CATEGORY_PENDING: "GET_CATEGORY_PENDING",
  GET_CATEGORY_FULFILLED: "GET_CATEGORY_FULFILLED",
  GET_CATEGORY_REJECTED: "GET_CATEGORY_REJECTED"
};
